version: '3.1'
services:
  mongo:
    image: mongo:4.2
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: db
    ports:
      - "27017:27017"
    volumes: 
      - E:/BusFlowDB/Mongo:/etc/mongo
  api:

  scrapper:

  frontend: